//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGG_ServerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CardList
    {
        public string ID { get; set; }
        public string Card_Number { get; set; }
        public Nullable<int> User_Status { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Client_ID { get; set; }
        public string WalnutUserIdentifier { get; set; }
        public string WalnutSubscriptionID { get; set; }
    }
}
