//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGG_ServerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubscriptionType
    {
        public string ID { get; set; }
        public string Subscription_Name { get; set; }
        public string Subscription_Description { get; set; }
        public string Subscription_Program { get; set; }
        public string Subscription_Price { get; set; }
        public string Subscription_Status { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Subscription_Recurring_Payment { get; set; }
    }
}
