//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGG_ServerEntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_Transaction
    {   
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string ID { get; set; }
        public string Card_Number { get; set; }
        public string Amount_Spend { get; set; }
        public Nullable<System.DateTime> Transaction_DateTime { get; set; }
        public string Station_Name { get; set; }
        public Nullable<int> Wash_Program { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Terminal_ID { get; set; }
        public string Client_Name { get; set; }
    }
}
