//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGG_ServerEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Client
    {
        public string ID { get; set; }
        public string Client_Name { get; set; }
        public string Invoice_Address { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string Client_UserName { get; set; }
        public string Client_EmailAddress { get; set; }
        public string Client_Folder_Address { get; set; }
        public string Client_UniqueString { get; set; }
        public string SubscriptionType_ID { get; set; }
    }
}
